"""Tests that every key of a config file is documented somewhere.

The configuration reference is generated by walking the config classes and
reading their field docstrings back out of the source, so the page cannot
disagree with the code --- but it can go quiet. A field added without a
docstring, or one whose description is inherited from a package that later
drops it, becomes a blank cell in a table nobody is watching, and the docs
build has no way to know that a missing description was not intended.

So the coverage is asserted here rather than at build time: a key without a
description fails on the commit that introduced it, next to the change that
caused it, instead of on whichever build somebody happens to read.

Deliberately not restricted to turbigen's own fields. Everything under
`solver:` is documented by ember, whose text this project quotes and does not
control, so this is also what says that an upgrade has taken a description
away --- at which point the field is restated here carrying one, as `n_step`
already is.

Test cases:
- test_every_key_has_a_description: no blank cells in the reference
- test_the_walk_reaches_the_whole_file: it is the same tree the page draws
- test_the_key_restated_to_document_it_behaves: and the restatement costs nothing
"""

import dataclasses
import typing

import pytest
from sphinx.pycode import ModuleAnalyzer

from turbigen.config import Config
from turbigen.node import Node
from turbigen.solver import Ember

DOCS = {}
"""Attribute docstrings, by module, read once per session."""


def attr_docs(module):
    """Return the attribute docstrings in `module`, keyed ``(class, field)``."""
    if module not in DOCS:
        analyzer = ModuleAnalyzer.for_module(module)
        analyzer.analyze()
        DOCS[module] = analyzer.find_attr_docs()
    return DOCS[module]


def described(cls, name):
    """Return whether field `name` of `cls` is documented anywhere in its MRO.

    The MRO, because a subclass restating a field to change its default writes
    no new docstring; the reference resolves a description the same way.
    """
    return any(
        attr_docs(base.__module__).get((base.__qualname__, name))
        for base in cls.__mro__
    )


def mappings(cls, seen=None):
    """Yield every class whose keys the config tree reaches, from `cls` down."""
    seen = set() if seen is None else seen
    if cls in seen:
        return
    seen.add(cls)

    yield cls

    alternatives = cls.options()
    if alternatives:
        for member in alternatives.values():
            yield from mappings(member, seen)
        return

    hints = typing.get_type_hints(cls)
    for field in dataclasses.fields(cls):
        for found in held_by(hints.get(field.name, field.type)):
            yield from mappings(found, seen)


def held_by(annotation):
    """Return the Node classes an annotation can hold."""
    found = []
    for arg in typing.get_args(annotation) or (annotation,):
        for inner in typing.get_args(arg) or (arg,):
            if isinstance(inner, type) and issubclass(inner, Node):
                found.append(inner)
    return found


def keys():
    """Return every ``(class, field name)`` a config file can be written with."""
    return [
        (cls, field.name)
        for cls in mappings(Config)
        if not cls.options()
        for field in dataclasses.fields(cls)
    ]


@pytest.mark.parametrize(
    "cls,name",
    keys(),
    ids=lambda item: item if isinstance(item, str) else item.__name__,
)
def test_every_key_has_a_description(cls, name):
    assert described(cls, name), (
        f"{cls.__name__}.{name} is a key a config file can be written with, "
        f"and nothing in its class hierarchy describes it. Give it a docstring, "
        f"or restate it here with one if it belongs to another package."
    )


def test_the_key_restated_to_document_it_behaves():
    """`Ember.n_step` is restated in turbigen only to carry a description.

    ember requires the field and describes it nowhere, so without the
    restatement the reference would have one blank cell, in the one key every
    solving run has to write. This is what says the restatement bought that
    description and changed nothing else: the field is still required, and
    still holds what a config gives it.
    """
    assert described(Ember, "n_step")

    with pytest.raises(TypeError):
        Ember()

    assert Ember(n_step=100).n_step == 100


def test_the_walk_reaches_the_whole_file():
    """Every top-level key of a config is reached by the walk above.

    Cheap, and it is what catches the walk quietly going blind --- an
    annotation spelled in a way `held_by` does not look through would drop a
    whole branch of the file out of both this test and the page, with nothing
    failing.
    """
    reached = set(mappings(Config))
    hints = typing.get_type_hints(Config)

    for field in dataclasses.fields(Config):
        for held in held_by(hints.get(field.name, field.type)):
            assert held in reached
