[project]
name = "turbigen"
version = "1.8.2"
requires-python = ">=3.9"
dependencies = [
    'CoolProp~=6.6.0',
    'matplotlib~=3.9.0',
    'numpy~=2.0.0',
    'PyYAML~=6.0.1',
    'scipy~=1.13.1',
    'h5py~=3.11.0',
    'numpy-stl~=3.1.1',
    'metis~=0.2a5',
]

[project.optional-dependencies]
docs = [
    'sphinx~=7.2.6',
    'sphinxcontrib-bibtex~=2.5.0',
    'sphinx-autobuild~=2021.3.14',
    'sphinx-argparse~=0.4.0',
    'sphinxcontrib-programoutput~=0.7',
]
test = [
    'pytest~=6.2.5',
    'pre-commit~=3.6.0',
]
embsolve = [
    'mpi4py',
]

[project.scripts]
turbigen = "turbigen.main:main"
turbigen-autogrid-server = "turbigen.autogrid.server:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# Only package what is in the turbigen folder
[tool.setuptools.packages.find]
include = ["turbigen",]
