!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.2.4)
!     It contains Fortran 90 wrappers to fortran functions.


      subroutine f2pyinitember(f2pysetupfunc)
      use ember, only : get_by_ijk
      use ember, only : average_by_ijk
      use ember, only : set_by_ijk
      use ember, only : node_to_face
      use ember, only : node_to_cell
      use ember, only : cell_to_node
      use ember, only : cell_to_face
      use ember, only : div
      use ember, only : grad
      use ember, only : smooth
      use ember, only : shear_stress
      use ember, only : viscous_flux
      use ember, only : wall_function
      use ember, only : zero_wall_stress
      use ember, only : set_fluxes
      use ember, only : add_pressure_fluxes
      use ember, only : sum_fluxes
      use ember, only : zero_wall_fluxes
      use ember, only : multigrid_integrate
      use ember, only : set_timesteps
      use ember, only : multigrid_indices
      use ember, only : multigrid_volumes
      use ember, only : smatvec
      use ember, only : smatmat
      use ember, only : dmatvec
      use ember, only : dmatmat
      use ember, only : residual
      use ember, only : step
      use ember, only : secondary
      use ember, only : damp
      external f2pysetupfunc
      call f2pysetupfunc(get_by_ijk,average_by_ijk,set_by_ijk,node_to_fa&
     &ce,node_to_cell,cell_to_node,cell_to_face,div,grad,smooth,shear_st&
     &ress,viscous_flux,wall_function,zero_wall_stress,set_fluxes,add_pr&
     &essure_fluxes,sum_fluxes,zero_wall_fluxes,multigrid_integrate,set_&
     &timesteps,multigrid_indices,multigrid_volumes,smatvec,smatmat,dmat&
     &vec,dmatmat,residual,step,secondary,damp)
      end subroutine f2pyinitember
